services:
  jenkins:
    build: ./Jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./Jenkins/jenkins-data:/var/jenkins_home
      - ./Jenkins/jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins
networks:
  jenkins: